// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTWiseAppV2.Data;

#nullable disable

namespace PTWiseAppV2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231205193954_AddedEntities")]
    partial class AddedEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PTWiseAppV2.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PTWiseAppV2.Data.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainerId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientId1");

                    b.HasIndex("TrainerId");

                    b.HasIndex("TrainerId1");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 6,
                            EndTime = new DateTime(2023, 11, 28, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2023, 11, 28, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Session 1",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 5,
                            EndTime = new DateTime(2023, 11, 28, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2023, 11, 28, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            Title = "Session 2",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 4,
                            EndTime = new DateTime(2023, 11, 30, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2023, 11, 30, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Session 3",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 2,
                            EndTime = new DateTime(2023, 12, 5, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2023, 12, 5, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            Title = "Session 4",
                            TrainerId = 2
                        });
                });

            modelBuilder.Entity("PTWiseAppV2.Data.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "100 Elgar Road",
                            Country = "United Kingdom",
                            DateOfBirth = new DateTime(2003, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kacermarciniak@gmail.com",
                            FirstName = "Kacper",
                            LastName = "Marciniak",
                            Postcode = "WR14 3EZ",
                            TelephoneNumber = "07465321286",
                            Title = "Mr",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "25 Oak Street",
                            Country = "United Kingdom",
                            DateOfBirth = new DateTime(1995, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.johnson@example.com",
                            FirstName = "Emily",
                            LastName = "Johnson",
                            Postcode = "AB12 3CD",
                            TelephoneNumber = "07894561234",
                            Title = "Ms",
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 3,
                            AddressLine1 = "15 Maple Avenue",
                            Country = "United Kingdom",
                            DateOfBirth = new DateTime(1988, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sophia.garcia@example.com",
                            FirstName = "Sophia",
                            LastName = "Garcia",
                            Postcode = "XY34 9AB",
                            TelephoneNumber = "07123456789",
                            Title = "Mrs",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 4,
                            AddressLine1 = "7 Pine Street",
                            Country = "United Kingdom",
                            DateOfBirth = new DateTime(1990, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "daniel.smith@example.com",
                            FirstName = "Daniel",
                            LastName = "Smith",
                            Postcode = "CD56 8EF",
                            TelephoneNumber = "07654321098",
                            Title = "Mr",
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 5,
                            AddressLine1 = "30 Elm Road",
                            Country = "United Kingdom",
                            DateOfBirth = new DateTime(2001, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "isabella.brown@example.com",
                            FirstName = "Isabella",
                            LastName = "Brown",
                            Postcode = "EF67 2GH",
                            TelephoneNumber = "07987654321",
                            Title = "Miss",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 6,
                            AddressLine1 = "12 Birch Lane",
                            Country = "United Kingdom",
                            DateOfBirth = new DateTime(1985, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "oliver.davis@example.com",
                            FirstName = "Oliver",
                            LastName = "Davis",
                            Postcode = "GH45 1IJ",
                            TelephoneNumber = "07234567890",
                            Title = "Mr",
                            TrainerId = 2
                        });
                });

            modelBuilder.Entity("PTWiseAppV2.Data.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestPeriodSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Difficulty = 0,
                            ExerciseType = 2,
                            Name = "Bench Press",
                            Reps = "6",
                            RestPeriodSeconds = 90,
                            Sets = 4,
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 2,
                            Difficulty = 0,
                            ExerciseType = 2,
                            Name = "Tricep Extensions",
                            Reps = "8",
                            RestPeriodSeconds = 60,
                            Sets = 5,
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 3,
                            Difficulty = 1,
                            ExerciseType = 2,
                            Name = "Squat",
                            Reps = "8",
                            RestPeriodSeconds = 120,
                            Sets = 4,
                            WorkoutId = 2
                        },
                        new
                        {
                            Id = 4,
                            Difficulty = 2,
                            ExerciseType = 2,
                            Name = "Deadlift",
                            Reps = "6",
                            RestPeriodSeconds = 120,
                            Sets = 4,
                            WorkoutId = 2
                        },
                        new
                        {
                            Id = 5,
                            Difficulty = 1,
                            ExerciseType = 2,
                            Name = "Pull-ups",
                            Reps = "10",
                            RestPeriodSeconds = 60,
                            Sets = 3,
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 6,
                            Difficulty = 1,
                            ExerciseType = 2,
                            Name = "Shoulder Press",
                            Reps = "8",
                            RestPeriodSeconds = 90,
                            Sets = 4,
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 7,
                            Difficulty = 0,
                            ExerciseType = 2,
                            Name = "Bicep Curls",
                            Reps = "10",
                            RestPeriodSeconds = 45,
                            Sets = 3,
                            WorkoutId = 2
                        },
                        new
                        {
                            Id = 8,
                            Difficulty = 1,
                            ExerciseType = 2,
                            Name = "Lunges",
                            Reps = "12",
                            RestPeriodSeconds = 60,
                            Sets = 3,
                            WorkoutId = 1
                        });
                });

            modelBuilder.Entity("PTWiseAppV2.Data.Entities.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GymName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "5 Geraldine Road",
                            Country = "United Kingdom",
                            DateOfBirth = new DateTime(1970, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johnpalmer@ptwise.com",
                            FirstName = "John",
                            GymName = "PT Wise Gym",
                            LastName = "Palmer",
                            Postcode = "WR14 3SZ",
                            TelephoneNumber = "1234567890",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "20 Burnout Close",
                            Country = "United Kingdom",
                            DateOfBirth = new DateTime(2002, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "benchadwick@ptwise.com",
                            FirstName = "Ben",
                            GymName = "PT Wise Gym",
                            LastName = "Chadwick",
                            Postcode = "WR14 1KT",
                            TelephoneNumber = "07496327386",
                            Title = "Mr"
                        });
                });

            modelBuilder.Entity("PTWiseAppV2.Data.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMins")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            Date = new DateTime(2023, 12, 5, 19, 39, 54, 684, DateTimeKind.Local).AddTicks(927),
                            DurationMins = 60,
                            Name = "Bombaclaat Belly Blast"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 2,
                            Date = new DateTime(2023, 12, 5, 19, 39, 54, 684, DateTimeKind.Local).AddTicks(973),
                            DurationMins = 60,
                            Name = "Marcin's Muscle Maker"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PTWiseAppV2.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PTWiseAppV2.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTWiseAppV2.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PTWiseAppV2.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PTWiseAppV2.Data.Entities.Appointment", b =>
                {
                    b.HasOne("PTWiseAppV2.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PTWiseAppV2.Data.Entities.Client", null)
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId1");

                    b.HasOne("PTWiseAppV2.Data.Entities.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PTWiseAppV2.Data.Entities.Trainer", null)
                        .WithMany("Appointments")
                        .HasForeignKey("TrainerId1");

                    b.Navigation("Client");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PTWiseAppV2.Data.Entities.Client", b =>
                {
                    b.HasOne("PTWiseAppV2.Data.Entities.Trainer", "Trainer")
                        .WithMany("Clients")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PTWiseAppV2.Data.Entities.Exercise", b =>
                {
                    b.HasOne("PTWiseAppV2.Data.Entities.Workout", "Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("PTWiseAppV2.Data.Entities.Workout", b =>
                {
                    b.HasOne("PTWiseAppV2.Data.Entities.Appointment", "Appointment")
                        .WithMany("Workouts")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("PTWiseAppV2.Data.Entities.Appointment", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("PTWiseAppV2.Data.Entities.Client", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("PTWiseAppV2.Data.Entities.Trainer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("PTWiseAppV2.Data.Entities.Workout", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
